apiVersion: production-stack.vllm.ai/v1alpha1
kind: VLLMRuntime
metadata:
  name: vllm-embedding
spec:
  model:
    modelURL: BAAI/bge-base-en-v1.5
    dtype: auto
  vllmConfig:
    gpuMemoryUtilization: "0.9"
  deploymentConfig:
    replicas: 1
    resources:
      cpu: "2"
      memory: 4Gi
      gpu: "1"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vllm-embedding
spec:
  rules:
  - host: embedding.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vllm-embedding
            port:
              number: 8000
